#usa una imagen base de Node.js
FROM node:18

#establece el directorio de trabajo
WORKDIR /app

#copia los archivos de configuración y dependencias primero
COPY package.json package-lock.json ./

#instala solo las dependencias de producción
RUN npm install --production


COPY . .

#expone el puerto 3000
EXPOSE 3000

#comando para iniciar el servidor
CMD ["npm", "start"]
